# Create Conda environment using:
  # conda env create -f environment_ros2.yml

name: fs_ros2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python version matches ROS2 Humble (Python 3.10)
  - python=3.10
  - pip
  - pip:
    - torch==2.4.1
    - torchvision==0.19.1
    - torchaudio==2.4.1
    - numpy
    - scikit-image
    - omegaconf
    - opencv-python-headless   # avoid GUI/GTK conflicts
    - imgaug
    - ninja
    - timm
    - albumentations
    - scipy
    - joblib
    - scikit-learn
    - ruamel.yaml
    - trimesh
    - pyyaml
    - imageio
    - open3d
    - transformations
    - einops
    - gdown
    - xformers==0.0.28.post1
    - huggingface-hub
    
    # Deep learning utilities
    - onnx==1.15.0
    - onnxruntime-gpu==1.23.0
    - tensorrt-cu12==10.13.3.9
    - pycuda==2025.1.2
    
    
