/**:
  ros__parameters:
    # Flash duration slider settings (ms)
    flash_duration:
      min: 0
      max: 300
      default: 170
      node: "/trigger_node"
      param:
        - "flash_duration_ms"
      service: "/trigger/set_flash_duration"
    
    # Frame rate slider settings (Hz)
    frame_rate:
      min: 1
      max: 20
      default: 3
      node: "/trigger_node"
      param:
        - "frame_rate_hz"
      service: "/trigger/set_frame_rate"
    
    # Firefly camera exposure settings (microseconds)
    firefly_exposure:
      min: 29
      max: 10000
      default: 417
      node: "/spinnaker_sync_node"
      param:
        - "firefly_left.exposure_time"
        - "firefly_right.exposure_time"
    
    # Ximea camera gain settings (dB)
    ximea_gain:
      min: -1.5
      max: 6.0
      default: 6.0
      step: 0.1
      node: "/ximea"
      param:
        - "gain"
    
    # Ximea camera exposure settings (microseconds)
    ximea_exposure:
      min: 50
      max: 500000
      default: 151223
      node: "/ximea"
      param:
        - "exposure_time"
    

