cmake_minimum_required(VERSION 3.8)
project(firefly-ros2-wrapper-bringup)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_components REQUIRED)
find_package(spinnaker_camera_driver REQUIRED)
find_package(spinnaker_synchronized_camera_driver REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(stereo_msgs REQUIRED)
find_package(cv_bridge REQUIRED)
find_package(message_filters REQUIRED)
find_package(image_geometry REQUIRED)
find_package(OpenCV REQUIRED)

# Add stereo disparity node
add_executable(stereo_disparity_node src/stereo_disparity_node.cpp)
ament_target_dependencies(stereo_disparity_node 
  rclcpp 
  sensor_msgs 
  stereo_msgs 
  cv_bridge 
  message_filters
  OpenCV)

# Add point cloud node
add_executable(point_cloud_node src/point_cloud_node.cpp)
ament_target_dependencies(point_cloud_node 
  rclcpp 
  sensor_msgs 
  stereo_msgs 
  cv_bridge 
  message_filters
  image_geometry
  OpenCV)

# Add flash simulator node
add_executable(flash_simulator_node src/flash_simulator_node.cpp)
ament_target_dependencies(flash_simulator_node 
  rclcpp 
  sensor_msgs 
  cv_bridge 
  message_filters
  OpenCV)

# Add depth cleaner node
add_executable(depth_cleaner_node src/depth_cleaner_node.cpp)
ament_target_dependencies(depth_cleaner_node 
  rclcpp 
  sensor_msgs 
  cv_bridge 
  OpenCV)

install(TARGETS
  stereo_disparity_node
  point_cloud_node
  flash_simulator_node
  depth_cleaner_node
  DESTINATION lib/${PROJECT_NAME})

# Install Python scripts
install(PROGRAMS
  scripts/fs_disparity_node.py
  DESTINATION lib/${PROJECT_NAME}
)

install (
  DIRECTORY calibs configs launch params rviz
  DESTINATION share/${PROJECT_NAME}
)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()